<center><h1> Série de Travaux Pratiques N° 7 - Machine Learning </h1></center>
<center><h2> K-Nearest Neighbor and Decision Tree</h2></center>

---



Pour ce TP, on utilisera le **dataset IRIS**. Ce dernier est une base de données regroupant les caractéristiques de **trois espèces de fleurs d’Iris, à savoir Setosa, Versicolour et Virginica**. Chaque ligne de ce jeu de données est une observation des caractéristiques d’une fleur d’Iris. Ce dataset décrit les espèces d’Iris par quatre propriétés : longueur et largeur de sépales ainsi que longueur et largeur de pétales. La base de données comporte 150 observations (50 observations par espèce).

# **Partie I : K-Nearest Neighbor**

# **Questions :**

1- Importer les packages nécessaires

2- Lire l'ensemble de données dans le dataframe pandas

3- Afficher et explorer l'ensemble de données "**iris.csv**"

4- Extraire les variables d'entrée X

5- Extraire les variables de sortie y

6- Diviser le dataset en Train / Test

7- Mise à l'échelle des fonctionnalités avec Transform()

8- Définir votre modèle **KNN**

9- Entraîner le modèle

10- Prédiction sur l'ensemble de test

11- Évaluation du modèle à l'aide de métriques

In [15]:
# IRIS Dataset : KNN


# 1- Importer les packages nécessaires 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# 2- Lire l'ensemble de données dans le dataframe pandas
data= pd.read_csv('iris.csv')

# 3- Afficher et explorer l'ensemble de données "**iris.csv**"
print (data.head())
# 4- Extraire les variables d'entrée X
X = data.iloc[:,:4]
print (X.head())
# 5- Extraire les variables de sortie y
Y = data.iloc[:,-1]
print (Y.head())
# 6- Diviser le dataset en Train / Test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.20)
# 7- Mise à l'échelle des fonctionnalités avec Transform()
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
# 8- Définir votre modèle KNN
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=40)

# 9- Entraîner le modèle
classifier.fit(X_train, Y_train)
# 10- Prédiction sur l'ensemble de test
Y_pred = classifier.predict(X_test)
# 11- Évaluation du modèle à l'aide de métriques
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print (confusion_matrix(Y_test,Y_pred))
print (classification_report(Y_test, Y_pred))
print (accuracy_score(Y_test, Y_pred)*100)
#12- Changer le K = {5, 10, 20, 30, 40}, que remarquez-vous?

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
   sepal.length  sepal.width  petal.length  petal.width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2
0    Setosa
1    Setosa
2    Setosa
3    Setosa
4    Setosa
Name: variety, dtype: object
[[ 5  0  0]
 [ 0  9  0]
 [ 0  4 12]]
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00         5
  Versicolor       0.69      1.00      0.82  

# **Partie II : Decision Trees**

# **Questions :**

1- Importer les packages nécessaires

2- Lire l'ensemble de données dans le dataframe pandas

3- Afficher et explorer l'ensemble de données "**iris.csv**"

4- Extraire les variables d'entrée X

5- Extraire les variables de sortie y

6- Diviser le dataset en Train / Test

7- Mise à l'échelle des fonctionnalités avec Transform()

8- Définir votre modèle **Decision Tree**

9- Entraîner le modèle

10- Prédiction sur l'ensemble de test

11- Évaluation du modèle à l'aide de métriques

In [2]:
# IRIS Dataset : Decision Tree


# 1- Importer les packages nécessaires
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# 2- Lire l'ensemble de données dans le dataframe pandas
data= pd.read_csv('iris.csv')
# 3- Afficher et explorer l'ensemble de données "iris.csv"
print (data.head())
# 4- Extraire les variables d'entrée X
X = data.iloc[:,:4]
print (X.head())
# 5- Extraire les variables de sortie y
Y = data.iloc[:,-1]
print (Y.head())
# 6- Diviser le dataset en Train / Test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.20)
# 7- Mise à l'échelle des fonctionnalités avec Transform()
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
# 8- Définir votre modèle Decision Trees
from sklearn.tree import DecisionTreeClassifier
treemodel = DecisionTreeClassifier()
# 9- Entraîner le modèle
treemodel.fit(X_train, Y_train)
# 10- Prédiction sur l'ensemble de test
Y_pred = treemodel.predict(X_test)
# 11- Évaluation du modèle à l'aide de métriques
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print (confusion_matrix(Y_test,Y_pred))
print (classification_report(Y_test, Y_pred))
print (accuracy_score(Y_test, Y_pred)*100)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
   sepal.length  sepal.width  petal.length  petal.width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2
0    Setosa
1    Setosa
2    Setosa
3    Setosa
4    Setosa
Name: variety, dtype: object
[[18  0  0]
 [ 0  6  0]
 [ 0  0  6]]
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        18
  Versicolor       1.00      1.00      1.00  